# -*- coding: utf-8 -*-
"""Untitled10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jmzcs-2zR-_RxOhkIjl7WZEMAebnthns
"""

import torch
import torch.nn as nn
import torch.nn.functional as F
import torchvision
import torchvision.transforms as transforms

# -----------------------------
# 1. Prunable Linear Layer
# -----------------------------
class PrunableLinear(nn.Module):
    def __init__(self, in_features, out_features):
        super().__init__()
        self.weight = nn.Parameter(torch.randn(out_features, in_features) * 0.01)
        self.bias = nn.Parameter(torch.zeros(out_features))
        self.gate_scores = nn.Parameter(torch.randn(out_features, in_features))

    def forward(self, x):
        gates = torch.sigmoid(self.gate_scores)  # values between 0 and 1
        pruned_weights = self.weight * gates
        return F.linear(x, pruned_weights, self.bias)


# -----------------------------
# 2. Model
# -----------------------------
class Net(nn.Module):
    def __init__(self):
        super().__init__()
        self.fc1 = PrunableLinear(784, 128)
        self.fc2 = PrunableLinear(128, 10)

    def forward(self, x):
        x = x.view(x.size(0), -1)  # flatten
        x = torch.relu(self.fc1(x))
        x = self.fc2(x)
        return x


# -----------------------------
# 3. Sparsity Loss (L1 on gates)
# -----------------------------
def sparsity_loss(model):
    loss = 0
    for m in model.modules():
        if isinstance(m, PrunableLinear):
            gates = torch.sigmoid(m.gate_scores)
            loss += gates.sum()
    return loss


# -----------------------------
# 4. Sparsity Calculation
# -----------------------------
def calculate_sparsity(model, threshold=0.01):
    total = 0
    zero = 0

    for m in model.modules():
        if isinstance(m, PrunableLinear):
            gates = torch.sigmoid(m.gate_scores)
            total += gates.numel()
            zero += (gates < threshold).sum().item()

    return 100 * zero / total


# -----------------------------
# 5. Data (MNIST for speed)
# -----------------------------
transform = transforms.ToTensor()

trainset = torchvision.datasets.MNIST(
    root='./data', train=True, download=True, transform=transform
)

testset = torchvision.datasets.MNIST(
    root='./data', train=False, download=True, transform=transform
)

trainloader = torch.utils.data.DataLoader(trainset, batch_size=64, shuffle=True)
testloader = torch.utils.data.DataLoader(testset, batch_size=64, shuffle=False)


# -----------------------------
# 6. Training Setup
# -----------------------------
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

model = Net().to(device)
optimizer = torch.optim.Adam(model.parameters(), lr=0.001)
lambda_ = 0.01  # sparsity strength


# -----------------------------
# 7. Training Loop
# -----------------------------
print("Training started...")

for epoch in range(1):  # keep 1 epoch (fast)
    model.train()
    total_loss = 0

    for images, labels in trainloader:
        images, labels = images.to(device), labels.to(device)

        optimizer.zero_grad()

        outputs = model(images)
        ce_loss = F.cross_entropy(outputs, labels)
        sp_loss = sparsity_loss(model)

        loss = ce_loss + lambda_ * sp_loss
        loss.backward()
        optimizer.step()

        total_loss += loss.item()

    print(f"Epoch {epoch+1} Loss: {total_loss:.4f}")

print("Training complete.\n")


# -----------------------------
# 8. Evaluation
# -----------------------------
model.eval()
correct = 0
total = 0

with torch.no_grad():
    for images, labels in testloader:
        images, labels = images.to(device), labels.to(device)

        outputs = model(images)
        _, predicted = torch.max(outputs, 1)

        total += labels.size(0)
        correct += (predicted == labels).sum().item()

accuracy = 100 * correct / total
sparsity = calculate_sparsity(model)

print(f"Test Accuracy: {accuracy:.2f}%")
print(f"Sparsity: {sparsity:.2f}%")